packages:
  - apps/*
  - packages/configs/*
  - packages/design-system/*
  - packages/libs/*
  - packages/plugins/*
allowBuilds:
  esbuild: set this to true or false
  lefthook: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  workerd: set this to true or false
ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - lefthook

saveExact: true
