packages:
  - apps/*
  - packages/configs/*
  - packages/design-system/*
  - packages/libs/*
  - packages/plugins/*

allowBuilds:
  "@parcel/watcher": false
  msgpackr-extract: false
  esbuild: false
  msw: false
  sharp: false
  unrs-resolver: false
  workerd: false

onlyBuiltDependencies:
  - lefthook

saveExact: true
