packages:
  - apps/*
  - packages/configs/*
  - packages/design-system/*
  - packages/libs/*
  - packages/plugins/*

ignoredBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver
  - workerd

onlyBuiltDependencies:
  - lefthook

saveExact: true
