packages:
  - apps/*
  - packages/configs/*
  - packages/design-system/*
  - packages/libs/*
  - packages/plugins/*

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - lefthook

saveExact: true
