import {
  base,
  effectAssertErrorFlip,
  exportRoleSuffixes,
  functional,
  importConfig,
  jsdoc,
  json,
  layerBoundary,
  logicFreeInboundAdapters,
  markdown,
  matchingTagIdentifier,
  namingConvention,
  noCoreSideEffects,
  noSingleDescribe,
  noThrowInProduction,
  node,
  outboundPartitioning,
  pathNamingConventions,
  singleFunctionPerFile,
  sonarjs,
  testDescriptionsJapanese,
  unicorn,
} from "@devstone/configs-eslint";
import { defineConfig } from "eslint/config";

const config = defineConfig(
  { ignores: ["dist/"] },
  {
    languageOptions: {
      parserOptions: {
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  base,
  effectAssertErrorFlip,
  exportRoleSuffixes,
  functional,
  importConfig,
  jsdoc,
  json,
  layerBoundary,
  logicFreeInboundAdapters,
  markdown,
  matchingTagIdentifier,
  namingConvention,
  noCoreSideEffects,
  noSingleDescribe,
  noThrowInProduction,
  node,
  outboundPartitioning,
  pathNamingConventions,
  singleFunctionPerFile,
  sonarjs,
  testDescriptionsJapanese,
  unicorn,
);

export default config;
