# FROM node:lts-bookworm
FROM debian:trixie

ARG REMOTE_USER
ARG REMOTE_WORKSPACES
ARG REMOTE_HOME

ENV PROTO_HOME=${REMOTE_HOME}/.proto
ENV PATH=${PATH}:${PROTO_HOME}/tools/node/globals/bin:${PROTO_HOME}/shims:${PROTO_HOME}/bin

# パッケージのインストール
# ------------------------------------------------------------------------------
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
  && apt-get install -y --no-install-recommends \
  ca-certificates curl gnupg less locales lsb-release sudo xz-utils jq zip unzip libatomic1 build-essential bubblewrap

# ユーザー設定
# ------------------------------------------------------------------------------
RUN useradd -m ${REMOTE_USER} -u 1000 -s /bin/bash
# ローカル開発環境のため許容している
RUN echo "${REMOTE_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# 日本語化対応
# ------------------------------------------------------------------------------
RUN sed -i -e 's/# \(ja_JP.UTF-8\)/\1/' /etc/locale.gen \
  && locale-gen \
  && update-locale LANG=ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8

# 永続化
# ------------------------------------------------------------------------------
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
  && mkdir -p /commandhistory ${REMOTE_HOME}/.vscode-server/extensions ${REMOTE_HOME}/.ssh \
  && touch /commandhistory/.bash_history \
  && chown -R ${REMOTE_USER}:${REMOTE_USER} /commandhistory ${REMOTE_HOME}/.vscode-server ${REMOTE_HOME}/.ssh \
  && echo ${SNIPPET} >> "${REMOTE_HOME}/.bashrc"

# ローカルにパッケージのインストール
# ------------------------------------------------------------------------------
USER ${REMOTE_USER}
ENV CODEX_NON_INTERACTIVE=true
ENV NTN_INSTALL_DIR="${REMOTE_HOME}/.local/bin"

RUN bash -c "$(curl -fsSL https://moonrepo.dev/install/proto.sh)" -- --yes
RUN bash -c "$(curl -fsSL https://claude.ai/install.sh)"
RUN bash -c "$(curl -fsSL https://antigravity.google/cli/install.sh)"
RUN bash -c "$(curl -fsSL https://cursor.com/install -fsS)"
RUN bash -c "$(curl -fsSL https://chatgpt.com/codex/install.sh)"
RUN bash -c "$(curl -fsSL https://ntn.dev)"
RUN sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes \
  && echo 'eval "$(starship init bash)"' >> ${REMOTE_HOME}/.bashrc

# プロンプトのカスタマイズ
# ------------------------------------------------------------------------------
RUN mkdir -p ${REMOTE_HOME}/.config \
  && { \
  echo '[time]'; \
  echo 'disabled = false'; \
  echo 'utc_time_offset = "9"'; \
  echo 'format = "🕘 [$time]($style) "'; \
  echo ''; \
  echo '[container]'; \
  echo 'format = "[$symbol]($style) "'; \
  echo ''; \
  echo '[nodejs]'; \
  echo 'format = "via [🏠 $version](bold green) "'; \
  } >> ${REMOTE_HOME}/.config/starship.toml
